########################################
# DIRECTORIES
########################################

# Define the root directory
ROOT_DIR ?= $(shell pwd)
export ROOT_DIR

# Directory for the output binaries
BUILD_DIR ?= $(ROOT_DIR)/build
export BUILD_DIR

# Source code root directory
SRC_ROOT_DIR ?= $(ROOT_DIR)/src
export SRC_ROOT_DIR

# Helper scripts directory
SCRIPTS_DIR ?= $(ROOT_DIR)/scripts
export SCRIPTS_DIR

# Externals (libraries) directory
EXT_DIR ?= $(ROOT_DIR)/ext
export EXT_DIR


#######################################
# googletest-SPECIFIC DEFINITIONS
#######################################

# Header directory for googletest
GTEST_INC_DIR ?= $(EXT_DIR)/googletest-svn/include
export GTEST_INC_DIR

# Path to the compiled googletest library (usually under
# "make" in the googletest directory in "ext").
GTEST_LIB ?= $(EXT_DIR)/googletest-svn/make/gtest_main.a
export GTEST_LIB

# This is necessary to work around a compilation issue with googletest when
# using clang and (presumably) libstdc++4.4
GTEST_FLAGS=-DGTEST_HAS_TR1_TUPLE=0


#######################################
# INCLUDES
#######################################

INCLUDES = -I$(SRC_ROOT_DIR) -I$(GTEST_INC_DIR)


#######################################
# LIBRARIES
#######################################

LIBS = -lgflags -lglog -ltcmalloc -lprofiler -lpthread


#######################################
# COMPILER
#######################################

CXX = clang++

CPPFLAGS = $(INCLUDES)

CXXFLAGS = $(LIBS) -Wall -Wextra -Werror -g -O0

